// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var sum = 0;
var first = 1;
var second = 2;

function fibonacci(upto) {
	do  {
		if (first % 2 == 0) {
			sum = sum + first;
		}
		let tmp = second;
		second = first + second;
		first = tmp;
	} while (first <= upto );
	console.log(sum);
}
fibonacci(4000000);
